---
application:
  name: "Akakce"
  url: "https://www.akakce.com/"
  username: "mozdamar90@hotmail.com"
  password: "aGdZx9.nMiKv9zG"

tests:
  dryrun: false
  tag: "@akakce"
  features: "src/test/resources/RegSuit/Akakce/"
  screenshots: "failure"    # failure  or  all

browser:
  name: "chrome"
  options:
    - "--start-maximized"


testerName: MO QA Team